# Site settings
title: walthamstow.me
tag_text: walthamstow,e17,community,london,john field
description: walthamstow.me

# Custom metadata
# https://help.github.com/articles/repository-metadata-on-github-pages/
googledoc_id: 1eDRE8QkbZO-GGAYzXCSDQfsz97DZtWqMJZDlbDQH_cU
ga_analytics_code: UA-94019156-1

# Build settings
markdown: kramdown
# exclude: ["README.md"]
sass:
  style: compressed
