# Site settings
title: walthamstow.me
keywords: walthamstow,e17,community,london,john field
description: A springboard site for Walthamstow, London

# Custom metadata - see https://help.github.com/articles/repository-metadata-on-github-pages/
# The ID of the Google Doc to be embedded. 
googledoc_id: 1eDRE8QkbZO-GGAYzXCSDQfsz97DZtWqMJZDlbDQH_cU
# Google Analytics code.
ga_code: UA-94019156-1

# Jekyll / GitHub Pages settings
baseurl: ""
markdown: kramdown
#exclude: ["README.md"]
sass:
  style: compact
  
# Don't use a GitHub Page theme by default.
#theme: jekyll-theme-minimal